"""initial schema

Revision ID: 524ccc47d371
Revises: 
Create Date: 2026-08-01 20:29:03.591740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '524ccc47d371'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('symptoms',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.Enum('PHYSICAL', 'EMOTIONAL', name='symptom_category'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('bbt_logs',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('temperature_celsius', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('time_recorded', sa.Time(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_bbt_log_user_date')
    )
    with op.batch_alter_table('bbt_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bbt_logs_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_bbt_logs_user_id'), ['user_id'], unique=False)

    op.create_table('cervical_mucus_logs',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('type', sa.Enum('DRY', 'STICKY', 'CREAMY', 'WATERY', 'EGG_WHITE', name='cervical_mucus_type'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_cervical_mucus_log_user_date')
    )
    with op.batch_alter_table('cervical_mucus_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cervical_mucus_logs_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_cervical_mucus_logs_user_id'), ['user_id'], unique=False)

    op.create_table('ovulation_test_logs',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('result', sa.Enum('NEGATIVE', 'POSITIVE', 'PEAK', name='ovulation_test_result'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_ovulation_test_log_user_date')
    )
    with op.batch_alter_table('ovulation_test_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ovulation_test_logs_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_ovulation_test_logs_user_id'), ['user_id'], unique=False)

    op.create_table('password_reset_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('period_entries',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('flow_intensity', sa.Enum('SPOTTING', 'LIGHT', 'MEDIUM', 'HEAVY', name='flow_intensity'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_period_entry_user_date')
    )
    with op.batch_alter_table('period_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_period_entries_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_period_entries_user_id'), ['user_id'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('symptom_logs',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('symptom_id', sa.Uuid(), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('severity >= 1 AND severity <= 5', name='ck_symptom_log_severity_range'),
    sa.ForeignKeyConstraint(['symptom_id'], ['symptoms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', 'symptom_id', name='uq_symptom_log_user_date_symptom')
    )
    with op.batch_alter_table('symptom_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_symptom_logs_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_symptom_logs_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('symptom_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_symptom_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_symptom_logs_date'))

    op.drop_table('symptom_logs')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_token_hash'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('period_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_period_entries_user_id'))
        batch_op.drop_index(batch_op.f('ix_period_entries_date'))

    op.drop_table('period_entries')
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_token_hash'))

    op.drop_table('password_reset_tokens')
    with op.batch_alter_table('ovulation_test_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ovulation_test_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_ovulation_test_logs_date'))

    op.drop_table('ovulation_test_logs')
    with op.batch_alter_table('cervical_mucus_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cervical_mucus_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_cervical_mucus_logs_date'))

    op.drop_table('cervical_mucus_logs')
    with op.batch_alter_table('bbt_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bbt_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_bbt_logs_date'))

    op.drop_table('bbt_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('symptoms')
    # ### end Alembic commands ###
